#=================================================================
# log 日志
#=================================================================
logging:
  config: classpath:logback-weblog.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weblog
    username: root
    password: 123123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  security:
    user:
      name: admin # 登录用户名
      password: 123456 # 登录密码
jwt:
   issuer: twentygao #签收人
    #密钥
   secret: oCZBHQ4B8ABQTWjhkKUy5hxAyElBgk0RVspPd4wIzfdBhqVUJGie5w3AaDZLUuCfiiHhaodhtApM2fErcU7uKg==
  # token 过期时间（单位：分钟） 24*60
   tokenExpireTime: 1440
  # token 请求头中的 key 值
   tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
   tokenPrefix: Bearer
